### ISSUE TITLE
Gimbricate segfaults on a particular GFA

### ISSUE THREAD

**Issue by RolandFaure** [ekg/gimbricate#4] opened 2020-08-04 06:27 UTC
We are running gimbricate on a graph produced by an assembler, with the line gimbricate -g assemblyGraph_k63.gfa -n -p h.paf -f h.fasta >h.gimbry.gfa. It segfaults after a few seconds.
When looking, it seems that it produced paf and fasta file correctly, and segfaulted after writing many sequences in h.gimbry.gfa but before writing the links. 
It does not seem to come from a RAM limitation error, as the segfault comes very quickly. Other graphs outputted by the same assembler ran fine with gimbricate, thus we suppose the error might come from a particular topological feature of the gfa. Do you know of any such limitation of gimbricate ?
Thanks in advance :)

**Comment by ekg** [comment] 2020-08-04 07:03
The only thing that comes to mind is a very long overlap that causes the
alignment to run out of memory. It doesn't actually eat through the memory,
but attempts to allocate a lot all at once and fails.

If you can share the GFA then I'd be able to confirm this.

I need to use edlib to derive the alignments. This has a banded mode and
can be much more memory efficient.

**Comment by RolandFaure** [comment] 2020-08-04 08:07
It is indeed a gfa with very long overlaps. The thing is, I am not actually using the master branch of gimbricate but the fork we made (ege-eeb fork, see issue #2 ), in which the Smith-Waterman algorithm is taken out in align.cpp, precisely to deal with large, perfect alignments (it segfaults in the same way in the ekg version of gimbricate). I checked,

 gimbricate segfaulted before ever going into align.cpp. 

Does that mean that gimbricate tries to allocate memory for SW before going into align.cpp ?
Or is that memory necessary for something else entirely ?

**Comment by ekg** [comment] 2020-08-04 08:21
I'll need to look at your fork. This could be caused by an error in the
construction of the GFA. For instance, if edges refer to nodes that do not
exist, or if the overlap that's specified is longer than one of the nodes.
If you use gdb where does it show the error occuring?

I do think it would be good to have edlib integrated. You can specify a
percent identity, and this is used to establish a bandwidth for the
alignment. You will also be able to confirm that the overlaps are exact.
But it's good to know that this isn't your problem here.

**Comment by RolandFaure** [comment] 2020-08-05 12:00
Using gdb, the error occurs : 
#3  0x0000555555581898 in std::function<void (gfak::edge_elem const&)>::operator()(gfak::edge_elem const&) const (__args#0=..., this=0x7fffffffc5e0)
    at /usr/include/c++/7/bits/std_function.h:706
#4  gfak::GFAKluge::for_each_edge_line_in_file(char*, std::function<void (gfak::edge_elem const&)>) (this=0x7fffffffc370, filename=<optimized out>, 
    func=...) at gimbricate/deps/gfakluge/src/gfakluge.hpp:936
#5  0x0000555555568d17 in main (argc=<optimized out>, argv=<optimized out>)
    at gimbricate/src/main.cpp:132

I've checked the GFA and found no overlaps longer than an edge or edges referring to non-existing nodes. Moreover all other GFA produced by the same assembler are processed without problem.

**Comment by ekg** [comment] 2020-08-05 13:38
This indicates an error when parsing an edge record. Would you please share
the GFA? I'll need to take a look at it.

**Comment by RolandFaure** [comment] 2020-08-05 14:19
https://mega.nz/file/eYdx3YzK#ZwG8uIRGMfZpYHB-ZS7Y9jFK8nJOTdAGO9VHWTHaxSk

Thank you very much for your time :)

**Comment by ekg** [comment] 2020-08-06 09:12
Would you have another mechanism to transfer the file rather than mega?
It's requiring that I create an account.

**Comment by RolandFaure** [comment] 2020-08-06 09:20
On wetransfer
https://we.tl/t-ZmTt1De3aM

**Comment by ekg** [comment] 2020-08-30 09:27
@RolandFaure the problem here was that your GFA file didn't have a header. Thus, the first record was skipped, but the link records associated with it were read. This caused the segfault.

```
(echo 'H\tVN:Z:1.0' ; cat assemblyGraph_k63.gfa) >assemblyGraph_k63.fixed.gfa
gimbricate -g assemblyGraph_k63.fixed.gfa -p assemblyGraph_k63.paf -f assemblyGraph_k63.fa -t 16 >assemblyGraph_k63.gimbry.gfa
```

This runs without issue (at least on the edlib-overlaps branch).

I've pushed a fix that will check that the header is present and the file is apparently GFAv1.

**Closed as completed** 2020-08-30 16:32 UTC
